spring:
  application:
    name: member-api
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8080/realms/spring-cloud-security/protocol/openid-connect/token/introspect
          client-id: api-application
          client-secret: NGpfseraiidpQVgLpANxNVnejgf4nWfm
         
server:
  port: 8093
  servlet:
    context-path: /api/member
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
