apiVersion: apps/v1
kind: Deployment
metadata:
  name:  single-service
spec:
  selector:
    matchLabels:
      app: single-service
  replicas: 1
  template:
    metadata:
      labels:
        app: single-service
    spec:
      containers:
        - name: single-service
          image: localhost:5001/jdc/single-service
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 8080
