apiVersion: v1
kind: Service
metadata:
  name: single-service
  namespace: default
spec:
  selector:
    app: single-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
